<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SSSLBG4NB466" failures="4" tests="7" name="CustomerLoginTests" time="13.269" errors="0" timestamp="2024-07-04T10:17:22 IST">
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="deposit" time="4.451"/>
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="deposit" time="0.669"/>
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="deposit" time="0.688">
    <failure type="java.lang.AssertionError" message="expected [invalid amount] but found [deposit successful]">
      <![CDATA[java.lang.AssertionError: expected [invalid amount] but found [deposit successful]
at com.sonata.CustomerLogin.Deposit.depositTesting1(Deposit.java:71)
at com.sonata.CustomerLogin.TestDriver.deposit(TestDriver.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deposit -->
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="deposit" time="0.434"/>
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="withdraw" time="1.115">
    <failure type="java.lang.AssertionError" message="expected [Transaction successful] but found [transaction successful]">
      <![CDATA[java.lang.AssertionError: expected [Transaction successful] but found [transaction successful]
at com.sonata.CustomerLogin.Withdraw.withdrawTesting1(Withdraw.java:83)
at com.sonata.CustomerLogin.TestDriver.withdraw(TestDriver.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- withdraw -->
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="withdraw" time="0.442">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.sonata.CustomerLogin.Withdraw.withdrawTesting1(Withdraw.java:76)
at com.sonata.CustomerLogin.TestDriver.withdraw(TestDriver.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- withdraw -->
  <testcase classname="com.sonata.CustomerLogin.TestDriver" name="transaction" time="1.234">
    <failure type="java.lang.AssertionError" message="expected [0] but found [5000]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [5000]
at com.sonata.CustomerLogin.Transaction.transactionTesting(Transaction.java:86)
at com.sonata.CustomerLogin.TestDriver.transaction(TestDriver.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- transaction -->
</testsuite> <!-- CustomerLoginTests -->
